name: Replace 'dev' with 'sit'

on:
  push:
    branches:
      - test1 

jobs:
  replace-word:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace 'dev' with 'sit' in text file
      run: |
       $filePath = 'sample.txt' 
       $wordToReplace = 'dev'
       $replacementWord = 'SIT'
       (Get-Content $filePath) -replace [regex]::Escape($wordToReplace), $replacementWord | Set-Content $filePath
       Get-Content $filePath

    
