name: Replace Words in File

on:
  workflow_dispatch:
    inputs:
      wordToReplace:
        description: 'Word to replace'
        required: true
        default: 'dev'
      replacementWord:
        description: 'Replacement word'
        required: true
        default: 'SIT'
  push:
    branches:
      - test

jobs:
  replace-word:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace words in text file
      run: |
        $filePath = 'sample.txt' 
        $wordToReplace = '${{ inputs.wordToReplace }}'
        $replacementWord = '${{ inputs.replacementWord }}'
        (Get-Content $filePath) -replace $wordToReplace, $replacementWord | Set-Content $filePath
        Get-Content $filePath
      env:
        wordToReplace: ${{ github.event.inputs.wordToReplace }}
        replacementWord: ${{ github.event.inputs.replacementWord }}
        
inputs:
  wordToReplace:
    description: 'dev'
    required: true
  replacementWord:
    description: 'SIT'
    required: true
