name: Replace 'dev' with 'sit'

on:
  push:
    branches:
      - test2  

jobs:
  replace-word:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace 'dev' with 'sit' in text file
      run: |
        filePath='sample.txt'
        wordToReplace='dev'
        replacementWord='sit'
        sed -i "s/$wordToReplace/$replacementWord/g" "$filePath"
        cat "$filePath"

    
