name: Replace 'dev' with 'sit'

on:
  push:
    branches:
      - main  

jobs:
  replace-word:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace 'dev' with 'sit' in text file
      run: |
        $filePath = 'sample.txt'  # Update with the path to your text document
        (Get-Content $filePath) -replace 'dev', 'sit' | Set-Content $filePath

    - name: Commit changes
      run: |
        git config --local user.email "anithish644@gmail.com" 
        git config --local user.name "Nithish007-bond" 
        git add sample.txt                   
        git commit -m "Replaced 'dev' with 'sit' in document.txt"
        git push
