name: Replace 'dev' with 'sit'

on:
  push:
    branches:
      - main  

jobs:
  replace-word:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Replace 'dev' with 'sit' in text file
      run: |
        $filePath = 'sample.txt'  
        (Get-Content $filePath) -replace 'dev', 'sit' | Set-Content $filePath
        Get-Content $filePath

    
